# Generated by Django 4.2.9 on 2025-12-29 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('client', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField()),
                ('thumbnail', models.ImageField(upload_to='portfolio/thumbnails/')),
                ('live_url', models.URLField(blank=True, help_text='Link to live website')),
                ('technologies', models.CharField(blank=True, help_text='Comma-separated: React, Next.js, etc.', max_length=255)),
                ('results', models.TextField(blank=True, help_text='Key results achieved')),
                ('is_published', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('completed_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Project Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='portfolio/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='portfolio.project')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='portfolio.projectcategory'),
        ),
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge', models.TextField(help_text='What problem did the client face?')),
                ('solution', models.TextField(help_text='How did we solve it?')),
                ('results', models.TextField(help_text='What were the outcomes?')),
                ('stat_1_label', models.CharField(blank=True, max_length=50)),
                ('stat_1_value', models.CharField(blank=True, max_length=50)),
                ('stat_2_label', models.CharField(blank=True, max_length=50)),
                ('stat_2_value', models.CharField(blank=True, max_length=50)),
                ('stat_3_label', models.CharField(blank=True, max_length=50)),
                ('stat_3_value', models.CharField(blank=True, max_length=50)),
                ('testimonial', models.TextField(blank=True)),
                ('testimonial_author', models.CharField(blank=True, max_length=100)),
                ('testimonial_position', models.CharField(blank=True, max_length=100)),
                ('is_published', models.BooleanField(default=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='case_study', to='portfolio.project')),
            ],
            options={
                'verbose_name_plural': 'Case Studies',
            },
        ),
    ]
