# Generated by Django 4.2.9 on 2025-12-29 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='technologies',
            field=models.JSONField(blank=True, default=list, help_text='List of technologies used'),
        ),
        migrations.AlterField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/thumbnails/'),
        ),
    ]
